[package]
name = "any_stream"
package.authors = "Adam Kaliszan adam.kaliszan@gmail.com"
package.description = "Single service loss system. Any type of arrival and service stream. This tool would provide height quality data for machine learning."
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
#map_first_last


[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
science = "0.1.0"
rand = "0.8.5"
rand_distr = "0.4.3"